name: Deploy to VPS

on:
  push:
    branches:
      - cicd

env:
  DOCKER_IMAGE: puneet2109/url-shorty
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:latest
          cache-to: type=inline

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/docker/url_shortener_alter_office
            # Stop and remove existing container
            docker compose down
            # Remove the existing image to force a new pull
            docker rmi puneet2109/url-shorty:latest || true
            docker rmi url_shortener_alter_office-app:latest || true
            # Pull the latest image
            docker compose pull
            # Start the services
            docker compose up -d
            # Clean up unused images
            docker image prune -f 